## [作業重點]
使用 Sklearn 中的線性迴歸模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義

## 作業
試著使用 sklearn datasets 的其他資料集 (wine, boston, ...)，來訓練自己的線性迴歸模型。

### HINT: 注意 label 的型態，確定資料集的目標是分類還是回歸，在使用正確的模型訓練！

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

import warnings
warnings.filterwarnings('ignore')

In [2]:
wine = datasets.load_wine()

# 切分訓練集/測試集
Wx_train, Wx_test, Wy_train, Wy_test = train_test_split(wine.data, wine.target, test_size=0.3, random_state=4)
print(Wx_train.shape)
Wy_train

(124, 13)


array([0, 1, 1, 1, 2, 2, 0, 2, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 2,
       0, 0, 1, 1, 2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 0, 1, 0, 1, 2, 2, 1, 1,
       1, 1, 1, 0, 2, 2, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 2, 0, 2, 1,
       2, 0, 2, 2, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 2, 2, 0, 1, 0, 2, 1, 2,
       1, 1, 1, 1, 0, 2, 0, 2, 1, 0, 2, 0, 1, 0, 2, 0, 0, 2, 0, 1, 0, 0,
       2, 0, 0, 1, 1, 1, 0, 2, 0, 1, 1, 1, 2, 1])

In [3]:
# 建立模型
logreg = linear_model.LogisticRegression()

# 訓練模型
logreg.fit(Wx_train, Wy_train)

# 預測測試集
Wy_pred = logreg.predict(Wx_test)

acc = accuracy_score(Wy_test, Wy_pred)
print("Accuracy: ", acc)

Accuracy:  0.9444444444444444


In [4]:


boston = datasets.load_boston()

Bx_train, Bx_test, By_train, By_test = train_test_split(boston.data, boston.target, test_size=0.3, random_state=4)
print(Bx_train.shape)
print(Bx_train)
By_train

(354, 13)
[[5.05900e-02 0.00000e+00 4.49000e+00 ... 1.85000e+01 3.96900e+02
  9.62000e+00]
 [4.30100e-02 8.00000e+01 1.91000e+00 ... 2.20000e+01 3.82800e+02
  8.05000e+00]
 [4.07710e-01 0.00000e+00 6.20000e+00 ... 1.74000e+01 3.95240e+02
  2.14600e+01]
 ...
 [9.39063e+00 0.00000e+00 1.81000e+01 ... 2.02000e+01 3.96900e+02
  2.28800e+01]
 [8.44700e-02 0.00000e+00 4.05000e+00 ... 1.66000e+01 3.93230e+02
  9.64000e+00]
 [9.29900e-02 0.00000e+00 2.56500e+01 ... 1.91000e+01 3.78090e+02
  1.79300e+01]]


array([23.9, 18.2, 21.7, 13.5, 50. , 23.1, 48.8, 13.8, 20.1, 50. , 34.9,
        8.4, 15.2, 23. , 24.7, 25.3, 17.2, 50. , 22.9, 20.2, 17.4, 19.5,
       18.5, 14. , 22.6, 14.1, 15.6, 46. , 20.5, 13.5, 10.4, 21.4, 21.6,
       23.2, 23. , 17.6, 16.1,  5. ,  8.3, 27.5, 18.7, 21.7, 30.7,  5. ,
       11.3,  7. , 32.9, 14.6, 12. , 28.1, 18. ,  5.6, 23.6, 24.7, 22.5,
       17.7, 13.1, 23.1, 25. , 14.9,  9.7, 22.8, 22. , 23.6, 14.3, 18.8,
       19.9, 13.6, 19.4, 16.8, 20. , 43.1, 27.9, 20.1, 19. , 19.2, 21.7,
       33.1, 50. , 33.2, 20.1, 21.1,  8.8, 12.3, 14.5, 23.8, 18.7, 21.8,
       21.9, 21.7, 17.1, 23.1, 36.1, 28.2, 11.5, 19. , 22. , 10.5, 21.4,
       16.5, 20.6, 23.3, 23.5, 15. , 26.5, 50. , 10.5, 17.5, 13.6, 17.2,
       19.1, 16.4, 20.6, 20.9, 30.1, 20.7, 22.2, 24.6, 25.2, 37.9, 20.1,
       29.6, 18.7, 23. , 22.9, 24.6, 24.8, 20.8, 22.4, 18.2, 14.4, 23.2,
       13. , 19.7, 21.2, 21.7, 24. , 22. , 20.6, 11.9, 24.3, 23.8, 22.8,
       13.3, 25. , 21. , 20.4, 33.1, 48.3, 14.5, 36

In [5]:
# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(Bx_train, By_train)

# 將測試資料丟進模型得到預測結果
By_pred = regr.predict(Bx_test)

# 可以看回歸模型的參數值
print('Coefficients: ', regr.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(By_test, By_pred))

Coefficients:  [-1.22569795e-01  5.56776996e-02 -8.83428230e-03  4.69344849e+00
 -1.44357828e+01  3.28008033e+00 -3.44778157e-03 -1.55214419e+00
  3.26249618e-01 -1.40665500e-02 -8.03274915e-01  9.35368715e-03
 -5.23477529e-01]
Mean squared error: 30.05


In [6]:
# 畫出回歸模型與實際資料的分佈
'''
plt.scatter(Bx_test, By_test,  color='black')
plt.plot(Bx_test, By_pred, color='blue', linewidth=3)
plt.show()
'''

"\nplt.scatter(Bx_test, By_test,  color='black')\nplt.plot(Bx_test, By_pred, color='blue', linewidth=3)\nplt.show()\n"

In [7]:
breast_cancer = datasets.load_breast_cancer()

BCx_train, BCx_test, BCy_train, BCy_test = train_test_split(breast_cancer.data, breast_cancer.target, test_size=0.3, random_state=4)

BCy_train

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,

In [8]:
# 建立模型
logreg = linear_model.LogisticRegression()

# 訓練模型
logreg.fit(BCx_train, BCy_train)

# 預測測試集
BCy_pred = logreg.predict(BCx_test)

acc = accuracy_score(BCy_test, BCy_pred)
print("Accuracy: ", acc)

Accuracy:  0.9181286549707602
